### ISSUE TITLE
Config repository missing

### ISSUE THREAD

**Issue by anitalpatil** [g00glen00b/microservice-demo#4]
Good microservice template it helped me. Actually I was looking for the microservice  template with angular 2 integrated one. Am able to understand the concept you used in it the thing is in config-service resource folder the application.yml file is having git repo link as "uri: git@github.com:g00glen00b/microservice-demo-config.git" am not able to get the configurations(like port number etc) of other microservices like discovery-service, gateway-service etc,. can you provide the repo  of the config.

**Comment by g00glen00b** [comment]
It should be available here: https://github.com/g00glen00b/microservice-demo-config
However, be aware that the project is not complete yet.

**Comment by anitalpatil** [comment]
Thanks for the replay, Spring Cloud Config Server provides a centralized configuration service that is horizontally scalable. It uses as its data store a pluggable repository layer that currently supports local storage, Git, and Subversion. By leveraging a version control system as a configuration store, developers can easily version and audit configuration changes.

for example in my microservice template am using central repository as "https://github.com/anitalpatil/anita-config" 

Where is your central repository?

**Comment by g00glen00b** [comment]
The repository I just mentioned is my central configuration repository: https://github.com/g00glen00b/microservice-demo-config
